### ISSUE TITLE
clean script

### ISSUE THREAD

**Issue by jfbabb** [compas/grasp#18]
In the clean script for example4, replace "cd ../tmp_mpi"
with " cd ./tmp_mpi"

**Comment by mortenpi** [comment]
Yep, this looks right to me. The `clean` script should not move away from the working directory: https://github.com/compas/grasp/blob/3a07ca18305cb11cb6988736a70dfc698321a60b/grasptest/example4/script/clean#L22-L24

Would you like to open a pull request with this fix?

**Comment by jongrumer** [comment]
Great, thanks @jfbabb - please open a pull request as suggested by @mortenpi. Do you mind me asking who you are? :) Your profile doesn't contain any info, and it's nice to know who we are collaborating with. Cheers!
