### ISSUE TITLE
"Maximum tabulation point exceeds dimensional limit (currently 590)"

### ISSUE THREAD

**Issue by pritivish** [compas/grasp#36]
Hello all, 
I am running the fine structure spitting calculation for I8+ (Z-53, 45 electrons, 4d9 ground state).
but when I am adding SD excitations from 4d(9,*) to 4f, 5s, 5p, 5d, 5f, 5g states. while running "rmcdhf" , it is showing following error. 

Lagrange multipliers:

                1s    5s                NaN
                2s    5s                NaN
                2p-   5p-               NaN
                2p    5p                NaN
                3s    5s                NaN
                3p-   5p-               NaN
                3p    5p                NaN
                3d-   5d-               NaN
                3d    5d                NaN
                4s    5s                NaN
                4p-   5p-               NaN
                4p    5p                NaN
                4d-   5d-               NaN
                4d    5d                NaN
                4f-   5f-               NaN
                4f    5f                NaN
                                         Self-            Damping
Subshell    Energy    Method   P0    consistency  Norm-1  factor  JP MTP INV NNP

 IN: maximum tabulation point exceeds
  dimensional limit (currently 590);
  radial wavefunction may indicate a
  continuum state.

**maybe doubly excited levels have the states above the ionization.  is GRASP is not able to perform energy calculation of those states".

**Comment by mortenpi** [comment]
Could you provide the exact inputs you used to `rnucleus`, `rcsfgenerate`, `rangular`, `rwfnestimate` and `rmcdhf`?

**Comment by pritivish** [comment]
yes, here are the inputs of the run 

**rnucleus**
Atomic number:
   53.000000000000000
Mass number (integer) :
   127.00000000000000
Fermi distribution parameter a:
  0.52338755531043146
Fermi distribution parameter c:
   5.6256236728328215
Mass of nucleus (in amu):
   126.87492526514100
Nuclear spin (I) (in units of h / 2 pi):
   2.5000000000000000
Nuclear dipole moment (in nuclear magnetons):
   2.8132799999999998
Nuclear quadrupole moment (in barns):
 -0.71099999999999997

**rcsfgenerate**
 * ! Orbital order
           4  ! Selected core
4d(9,*)
*
5s, 5p, 5d, 5f, 5g
           1          21  ! Lower and higher 2*J
           2  ! Number of excitations
n
( Group CSFs into symmetry blocks
11 blocks were created
       block  J/P            NCSF
           1  1/2+            830
           2  3/2+           1513
           3  5/2+           1940
           4  7/2+           2061
           5  9/2+           1929
           6 11/2+           1597
           7 13/2+           1194
           8 15/2+            795
           9 17/2+            475
          10 19/2+            244
          11 21/2+            111 )

**rcsfinteract**
 RCSFinteract: Determines all the CSFs (rcsf.inp) that interact
               with the CSFs in the multireference (rcsfmr.inp)
               (C)  Copyright by G. Gaigalas and Ch. F. Fischer
               (Fortran 95 version)               NIST  (2017).
               Input files: rcsfmr.inp, rcsf.inp
               Output file: rcsf.out
 
 Reduction based on Dirac-Coulomb (1) or
 Dirac-Coulomb-Breit (2) Hamiltonian?
2
 Loading Configuration Symmetry List File ...
 There are 25 relativistic subshells;
  Block    MR NCSF   Before NCSF   After NCSF
    1            1          830            1
    2            1         1513            1

 Wall time:
        1 seconds

 Finish Date and Time:
   Date (Yr/Mon/Day): 2020/02/03
   Time (Hr/Min/Sec): 09/35/27.984
   Zone: +0900

 RCSFinteract: Execution complete.

**rangular**
y            ! Full interaction
 
**rwfnestimate**
This program estimates radial wave functions
 for orbitals
 Input files: isodata, rcsf.inp, optional rwfn file
 Output file: rwfn.inp
 Default settings ?
y
 Loading CSF file ... Header only
 There are/is           25  relativistic subshells;
 The following subshell radial wavefunctions remain to be estimated:
 1s 2s 2p- 2p 3s 3p- 3p 3d- 3d 4s 4p- 4p 4d- 4d 4f- 4f 5s 5p- 5p 5d- 5d 5f- 5f
 5g- 5g

 Read subshell radial wavefunctions. Choose one below
     1 -- GRASP92 File
     2 -- Thomas-Fermi
     3 -- Screened Hydrogenic
1
 Enter the file name (Null then "rwfn.out")
DF.w
_(here, DF.w is previous run only for 4d9 configuration, for which initial wavefunction is obtained by DBSR_HF and then obtained by running mchdf default)_ 

 Enter the list of relativistic subshells:
*
 The following subshell radial wavefunctions remain to be estimated:
 4f- 4f 5s 5p- 5p 5d- 5d 5f- 5f 5g- 5g

 Read subshell radial wavefunctions. Choose one below
     1 -- GRASP92 File
     2 -- Thomas-Fermi
     3 -- Screened Hydrogenic
2
 Enter the list of relativistic subshells:
*

**rmcdhf**
RMCDHF
 This program determines the radial orbitals   
 and the expansion coefficients of the CSFs         
 in a self-onsistent field proceedure               
 Input file:  isodata, rcsf.inp, rwfn.inp, mcp.30, ...
 Outputfiles: rwfn.out, rmix.out, rmcdhf.sum, rmcdhf.log

Default settings?  (y/n) y
 Loading CSF file ... Header only
 There are/is           25  relativistic subshells;
 Loading CSF File for ALL blocks 
 Subshell 4f- is empty in all CSFs
 Subshell 4f  is empty in all CSFs
 Subshell 5s  is empty in all CSFs
 Subshell 5p- is empty in all CSFs
 Subshell 5p  is empty in all CSFs
 Subshell 5d- is empty in all CSFs
 Subshell 5d  is empty in all CSFs
 Subshell 5f- is empty in all CSFs
 Subshell 5f  is empty in all CSFs
 Subshell 5g- is empty in all CSFs
 Subshell 5g  is empty in all CSFs
 There are            2  relativistic CSFs... load complete;
 Loading Radial WaveFunction File ...
 There are            2  blocks  (block   J/Parity   NCF):
  1  3/2+       1       2  5/2+       1

 Enter ASF serial numbers for each block
 Block            1    ncf =            1  id =  3/2+
1-1
 Block            2    ncf =            1  id =  5/2+
1-1
 level weights (1 equal;  5 standard;  9 user)
5
 Radial functions
 1s 2s 2p- 2p 3s 3p- 3p 3d- 3d 4s 4p- 4p 4d- 4d 4f- 4f 5s 5p- 5p 5d- 5d 5f- 5f
 5g- 5g
 Enter orbitals to be varied (Updating order)
4f- 4f 5s 5p- 5p 5d- 5d 5f- 5f 5g- 5g 
 Which of these are spectroscopic orbitals?

 Enter the maximum number of SCF cycles:
100

 Average energy =  -7.0990460782D+03 Hartrees
 Average energy =  -7.0991125676D+03 Hartrees

Optimise on the following level(s):

Level  1    Energy = -7.099046078171D+03    Weight =  4.00000D-01
Level  1    Energy = -7.099112567638D+03    Weight =  6.00000D-01

Weights of major contributors to ASF:

Block Level J Parity      CSF contributions

  1     1   3/2 +       1.0000
                             1
  2     1   5/2 +       1.0000
                             1

Weighted average energy of these levels =  -7.0990859719D+03

Generalised occupation numbers:

   2.0000D+00  2.0000D+00  2.0000D+00  4.0000D+00  2.0000D+00  2.0000D+00
   4.0000D+00  4.0000D+00  6.0000D+00  2.0000D+00  2.0000D+00  4.0000D+00
   3.6000D+00  5.4000D+00  0.0000D+00  0.0000D+00  0.0000D+00  0.0000D+00
   0.0000D+00  0.0000D+00  0.0000D+00  0.0000D+00  0.0000D+00  0.0000D+00
   0.0000D+00

 Iteration number   1
 --------------------

Include Lagrange multipliers between:

                1s    5s 
                2s    5s 
                2p-   5p-
                2p    5p 
                3s    5s 
                3p-   5p-
                3p    5p 
                3d-   5d-
                3d    5d 
                4s    5s 
                4p-   5p-
                4p    5p 
                4d-   5d-
                4d    5d 
                4f-   5f-
                4f    5f 

Lagrange multipliers:

                1s    5s                NaN
                2s    5s                NaN
                2p-   5p-               NaN
                2p    5p                NaN
                3s    5s                NaN
                3p-   5p-               NaN
                3p    5p                NaN
                3d-   5d-               NaN
                3d    5d                NaN
                4s    5s                NaN
                4p-   5p-               NaN
                4p    5p                NaN
                4d-   5d-               NaN
                4d    5d                NaN
                4f-   5f-               NaN
                4f    5f                NaN
                                         Self-            Damping
Subshell    Energy    Method   P0    consistency  Norm-1  factor  JP MTP INV NNP

 IN: maximum tabulation point exceeds
  dimensional limit (currently 590);
  radial wavefunction may indicate a
  continuum state.

**Comment by mortenpi** [comment]
If it is as simple as running out of gridpoints, you could try making the grid bigger in [`parameter_def`](https://github.com/compas/grasp/blob/master/src/lib/libmod/parameter_def_M.f90) and recompile GRASP. I gave it a try, but I couldn't actually even get the multireference to converge, so I'll have to leave this for someone else to check out.

**Comment by pritivish** [comment]
Thank you so much Morten. 
I am able to run it now.
However, for convergence as mentioned in the manual first I have generated the wavefunction from DBSR code, utilizing that in rwfnestimate I got the convergence.
