### ISSUE TITLE
Example1 not working 

### ISSUE THREAD

**Issue by amilton10** [compas/grasp#39]
I am  starting with GRASP now so excuse me if i am saying something absurd.
After i have installed GRASP i ran the script of example1 : ./script_ex1 >& output &  
After that i ran the command  rmcdhf but i am getting the following error 

Method 2 unable to solve for  3s  orbital
 Iteration number:  9, limit:  9
 Present estimate of P0;  0.22117473513882D+00
 Present estimate of E(J):  0.34218606921520D+00, DELEPS:  0.57599776608896D-02
 Lower bound on energy:  0.91488178055281D-01, upper bound:  0.72009664241632D+00
 Join point:  315, Maximum tabulation point: 372
 Number of nodes counted:  2, Correct number:  2
 Sign of P at first oscillation: -1.

 Failure; equation for orbital  3s  could not be solved using method 2

 ****** Error in SUBROUTINE IMPROV ******
 Convergence not obtained

**Comment by mortenpi** [comment]
> After that i ran the command rmcdhf

What options did you use?

That being said, running another round of `rmcdhf` is not really part of the example anymore, as far as I can tell, so I wouldn't say that example is in any way broken. I also ran ` ./script_ex1` with the latest master and it seems to run fine.
